### ISSUE TITLE
Requires libsteam_api.so to run

### ISSUE THREAD

**Issue by pkillnine** [a327ex/BYTEPATH#3]
I can't run it without providing libsteam_api.so by running it directly with LOVE. It would be good to not require it.

I provide it using goldberg emulator (adding it's /lib directory to LD_LIBRARY_PATH) currently, which works great and is FOSS: https://mr_goldberg.gitlab.io/goldberg_emulator/

**Comment by seletz** [comment]
Comment out the first two lines in main.lua and replace with
```lua
Steam = nil
```

**Comment by a327ex** [comment]
Check out [this comment](https://www.reddit.com/r/linux_gaming/comments/hlwzjn/bytepath_a_replayable_arcade_shooter_with_a_focus/fx2j1ss/) on reddit too
